[16기 김준형] signup 추가
wecode-bootcamp-korea/16-2nd-market-ssua-backend pull request #2
Opened 2021-01-27 07:44 UTC by ddalkigum

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)

		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- id '@' 포함, pw 5 글자 이상 입력 시 버튼 활성화(예시)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.

2021-01-28 02:18 UTC, lordmyshepherd requested changes

2021-01-28 02:18 UTC, lordmyshepherd commented on market_ssua/urls.py
> +    path("user", include("users.urls"))
URI 첫번째 계층은 복수로 만들어주세요~
```suggestion
    path("users", include("users.urls"))
```

2021-01-28 02:18 UTC, lordmyshepherd commented on users/tests.py
> +        clean_password = bcrypt.hashpw("wecode123".encode("utf-8"), salt = bcrypt.gensalt()).decode()
`password`를 `hashing`해서 전달해주는 이유가 있나요?
```suggestion
        clean_password = bcrypt.hashpw("wecode123".encode("utf-8"), salt = bcrypt.gensalt()).decode()
```

2021-01-28 02:18 UTC, lordmyshepherd commented on users/tests.py
> +        Grade.objects.create(name = "일반", accur_rate = 1, id = 6)
id = 6으로 넣어주는 이유가 무엇인가요??

2021-01-28 02:18 UTC, lordmyshepherd commented on users/tests.py
> +    def setUp(self):
**setUp()**
`TestCase`를 상속받은 경우, `setUp()`은 각각의 `test_method`가 실행될 때마다 실행됩니다. 
그렇기 때문에 테스트 중에 내용이 변경될 수 있는 객체를 생성할 수 있습니다.
ex)
```python
    def setUp(self):
        user = User.objects.create(name="a")

    def test_xxxx(self):
        user.name = "b"
        user.save()
        ....
```
이런 경우가 아니라면, 즉 test 전체에서 사용되는 수정되거나 변경되지 않을 객체들을 생성하는 경우에 `setUp`에서 객체를 생성하게 되면 매번 객체를 생성하게 되므로 느려집니다.

**setUpTestData()**
테스트에서 읽기 전용 데이터로만 사용하는 객체의 경우 class method인 `setUpTestData`를 사용하면 한번만 생성할 수 있게 되므로 테스트 처리 속도가 빨라집니다.
가급적이면 `setUp`에서 매번 객체를 생성하는 것을 지양하는 것이 좋습니다.

2021-01-28 02:23 UTC, ddalkigum commented on market_ssua/urls.py
> +    path("user", include("users.urls"))
넵 알겠습니다 😁

2021-01-28 02:24 UTC, ddalkigum commented on users/tests.py
> +        clean_password = bcrypt.hashpw("wecode123".encode("utf-8"), salt = bcrypt.gensalt()).decode()
저희가 비밀번호를 hashing해서 저장해 주기 때문에 테스트로 해싱한 걸 확인해야 할 것 같아서 저장했습니다

2021-01-28 02:25 UTC, ddalkigum commented on users/tests.py
> +        Grade.objects.create(name = "일반", accur_rate = 1, id = 6)
유저등급이 6가지 있는데 회원가입을 했을때 기본적으로 가장 밑에 등급인 일반등급으로 들어가기 때문에 
id = 6인 등급으로 들어가게 만들었습니다

2021-01-28 02:27 UTC, ddalkigum commented on users/tests.py
> +    def setUp(self):
아아... 넵 공식문서 보고 수정해서 올릴게요!

2021-01-28 06:37 UTC, ddalkigum commented on users/tests.py
> +    def setUp(self):
이거 해보니까 setUp으로 했을때는 2.2초 정도 됬었는데 
수정하고 나서 0.8초 정도로 줄었어요!

2021-01-29 01:25 UTC, lordmyshepherd commented on users/tests.py
> +    def setUp(self):
실행속도까지 테스트 해보셨군요!! 준형님👍

2021-01-29 01:33 UTC, lordmyshepherd approved these changes

2021-01-29 01:33 UTC, lordmyshepherd commented
LGTM 👍

2021-01-29 01:35 UTC, lordmyshepherd approved these changes

2021-01-29 08:13 UTC, lordmyshepherd commented
LGTM: 👍

2021-01-29 08:13 UTC, merged