[16기 최수아] Add : productview
wecode-bootcamp-korea/16-2nd-market-ssua-backend pull request #4
Opened 2021-01-27 15:57 UTC by sue517

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- product 상세페이지 view
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.

2021-01-28 01:56 UTC, soheon-lee commented on products/urls.py
> +    path('/<int:product_group_id>', ProductView.as_view()),
```suggestion
    path('/group/<int:product_group_id>', ProductView.as_view()),
```
products라는 url뒤에 바로 숫자가 오면, RESTful URL규칙상 상세 상품의 데이터가 됩니다 :)
따라서 앞에 `group`이 있는 것이 보다 이해하기 쉽겠어요!

2021-01-28 01:56 UTC, soheon-lee commented on products/views.py
> +from .models          import Product, ProductGroup, ProductGroupImage, ProductGroupPackageType, Relation
import 하는 클래스가 많아서 개별 라인으로 분리해주시는 것이 좋겠습니다

2021-01-28 01:56 UTC, soheon-lee commented on products/views.py
> +
이미 14번째 줄에서 ProductGroup 객체를 하나 특정하셨고, `Product`, `ProductGroupImage`, `ProductGroupPackageType` 클래스는 ProductGroup과 모두 직간접적으로 연결이 되어있습니다. 이럴 경우에는 ProductGroup의 속성을 이용하셔서 연결된 객체들을 타고 들어가서 데이터를 꺼내오시는 것이 좋습니다 :)
각 클래스에 한 번 접근할 때마다 쿼리가 발생하기 때문에 이 횟수를 최대한 줄이시는 것이 좋습니다!

2021-01-28 01:56 UTC, soheon-lee commented on products/views.py
> +            }
`for i in range(len(related_products))` 안하셔도 :) 바로 위에 product 꺼내오셨듯이 바로 객체하나씩 꺼내시면 될 것 같아요!

2021-01-28 01:56 UTC, soheon-lee commented on products/views.py
> +            }
JSON 구조 완전 깔끔하고 대박

2021-01-28 01:56 UTC, soheon-lee commented on products/views.py
> +            return JsonResponse({"error": "PRODUCT_DOES_NOT_EXIST"}, status=400)
`PRODUCT_DOES_NOT_EXIST` 에러 언제 발생하나요?
포스트맨이나 httpie로 테스트 해보셨나요? 발생된 상황 postman이나 httpie 캡처해서 보여주세요 :)

2021-01-28 02:07 UTC, sue517 commented on products/urls.py
> +    path('/<int:product_group_id>', ProductView.as_view()),
소헌님 이게 상세 상품의 데이터가 맞아요!
마켓컬리는 `product group` 안에 상세 상품을 선택하게 되어있는거라 `product group` 전체의 `description` 은 공유하고 상세 상품 페이지가 따로 존재하지 않아서 결과적으로는 `group_id` 로 들어가는 페이지 = 상세상품 페이지 라고 판단하여 요런 식으로 url 을 넣었습니다😁...! 바꾸는게 좀 더 명확할까용?

2021-01-28 02:07 UTC, sue517 commented on products/views.py
> +            return JsonResponse({"error": "PRODUCT_DOES_NOT_EXIST"}, status=400)
요기에 캡쳐 이미지가 안올라가서 코드 복붙합니댜! db에 상품이 없는 상태로 `/products/1` 진행하면 (아무 product_group_id 넣어서) 하면 이렇게 뜹니다...!

```
January 28, 2021 - 10:39:07
Django version 3.1.5, using settings 'market_ssua.settings'
Starting development server at http://0:8000/
Quit the server with CONTROL-C.
Internal Server Error: /products/1
Traceback (most recent call last):
  File "/Users/sua/desktop/sua/enter/Users/sua/envs/kurly/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/sua/desktop/sua/enter/Users/sua/envs/kurly/lib/python3.7/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/sua/desktop/sua/enter/Users/sua/envs/kurly/lib/python3.7/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/sua/desktop/sua/enter/Users/sua/envs/kurly/lib/python3.7/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/sua/16-2nd-market-ssua-backend/products/views.py", line 15, in get
    product_groups    = ProductGroup.objects.get(id = pgid)
  File "/Users/sua/desktop/sua/enter/Users/sua/envs/kurly/lib/python3.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/sua/desktop/sua/enter/Users/sua/envs/kurly/lib/python3.7/site-packages/django/db/models/query.py", line 431, in get
    self.model._meta.object_name
products.models.ProductGroup.DoesNotExist: ProductGroup matching query does not exist.
[28/Jan/2021 10:39:09] "GET /products/1 HTTP/1.1" 500 79651
```

2021-01-28 02:08 UTC, sue517 commented on products/views.py
> +            return JsonResponse({"error": "PRODUCT_DOES_NOT_EXIST"}, status=400)
unit test 는 오후 세션 이후에 추가하겠습니다 :>

2021-01-29 01:47 UTC, lordmyshepherd commented on products/urls.py
> +    path('/<int:product_group_id>', ProductView.as_view()),
수아님! **데이터 기준**으로 생각해보면, 명확히는 `product group 리스트`에서 `하나의 product group`을 선택하면 상세 페이지를 반환해주죠. 정확히는 상품이 아니라 `상품 그룹`입니다. 그렇기 때문에 URI는 `product-group/<int:product_group_id>`가 되야 합니다.

2021-01-29 02:10 UTC, lordmyshepherd requested changes

2021-01-29 02:10 UTC, lordmyshepherd commented on products/views.py
> +            pgid = product_group_id
```suggestion
```

2021-01-29 02:10 UTC, lordmyshepherd commented on products/views.py
> +            product_groups   = ProductGroup.objects.get(id = pgid)
변수 선언시 단수, 복수를 잘 지켜주세요~
```suggestion
            product_group   = ProductGroup.objects.get(id = product_group_id)
```

2021-01-29 02:10 UTC, lordmyshepherd commented on products/views.py
> +                } for product in products],
```suggestion
                "products" : [{
                    "id"         : product.id,
                    "name"       : product.name,
                    "price"      : product.price,
                    "sold_out"   : product.sold_out,
                    "ingredient" : product.ingredient,
                    "point"      : product.point
                } for product in product_group.product_set.all()],
```

2021-01-29 02:10 UTC, lordmyshepherd commented on products/views.py
> +            related_products = product_groups.relate.all()
`get() handler method 내에서 다시 사용되지 않는다면, 각 변수에 할당해줄 필요 없을 것 같습니다.

2021-01-29 02:10 UTC, lordmyshepherd commented on products/views.py
> +            product_detail = {
```suggestion
            result = {
```

2021-01-29 02:10 UTC, lordmyshepherd commented on products/views.py
> +                } for image in images],
```suggestion
                "product_group_images" : [{
                    "url" : image.url
                } for image in product_groups.productgroupimage_set.all()],
```

2021-01-29 02:10 UTC, lordmyshepherd commented on products/views.py
> +            related_products = product_groups.relate.all()
```suggestion
```

2021-01-29 02:10 UTC, lordmyshepherd commented on products/tests.py
> +
**setUp()**
`TestCase`를 상속받은 경우, `setUp()`은 각각의 `test_method`가 실행될 때마다 실행됩니다. 
그렇기 때문에 테스트 중에 내용이 변경될 수 있는 객체를 생성할 수 있습니다.
ex)
```python
    def setUp(self):
        user = User.objects.create(name="a")

    def test_xxxx(self):
        user.name = "b"
        user.save()
        ....
```
이런 경우가 아니라면, 즉 test 전체에서 사용되는 수정되거나 변경되지 않을 객체들을 생성하는 경우에 `setUp`에서 객체를 생성하게 되면 매번 객체를 생성하게 되므로 느려집니다.

**setUpTestData()**
테스트에서 읽기 전용 데이터로만 사용하는 객체의 경우 class method인 `setUpTestData`를 사용하면 한번만 생성할 수 있게 되므로 테스트 처리 속도가 빨라집니다.
가급적이면 `setUp`에서 매번 객체를 생성하는 것을 지양하는 것이 좋습니다.

2021-02-01 02:30 UTC, lordmyshepherd approved these changes

2021-02-01 02:30 UTC, lordmyshepherd commented on products/views.py
> +                } for releated_product in product_group.related.all()]
이부분에서 `database`를 `hit`하는 횟수를 파악해보고, `select_related` 또는 `prefetch_related`를 적용해보면 어떨까요??

2021-02-01 09:15 UTC, sue517 commented on products/views.py
> +                } for releated_product in product_group.related.all()]
적용했습니다 감사합니다 😁

2021-02-02 02:55 UTC, lordmyshepherd approved these changes

2021-02-02 02:59 UTC, lordmyshepherd approved these changes

2021-02-02 02:59 UTC, lordmyshepherd commented
LGTM 👍

2021-02-02 02:59 UTC, merged