[16기 김준형] 장바구니 기능 추가
wecode-bootcamp-korea/16-2nd-market-ssua-backend pull request #7
Opened 2021-01-30 15:53 UTC by ddalkigum

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
 
- 레디스 적용 
- 장바구니 유닛테스트 완료 
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.

2021-02-01 02:21 UTC, lordmyshepherd requested changes

2021-02-01 02:21 UTC, lordmyshepherd commented on decorators/utils.py
> +import json
#5 pull request에 이미 포함된 코드처럼 보이네요.

2021-02-01 02:21 UTC, lordmyshepherd commented on orders/tests.py
> +        self.order_item.save()
TestCase 정말 잘 장성해 주셨네요!
`line 170~171`에서보면, `setUpTestData`에서 생성한 데이터는 모든 테스트 케이스에서 공유하는 읽기 전용으로 만들어야되는 데이터입니다. `test_get_user_order_products_none_delivery_price` 테스트와 다음에 진행되는 테스트 사이에 의존성이 생기게 됩니다.
테스트 중간에 수정해야될 데이터가 있다면 `setUp`을 사용하시거나, 아니면 테스트 케이스 내에서 만들어주세요.
이런 경우는 테스트케이스 내에서 생성하는 것을 추천드립니다.

2021-02-01 02:21 UTC, lordmyshepherd commented on products/models.py
> +        return self.price
`@property` decorator를 적용해보시면 어떨까요?

2021-02-01 02:21 UTC, lordmyshepherd commented on users/models.py
> +        ExpressionWrapper(Ceil(Sum((F("orderitem__product__price") *
`ExpressionWrapper`를 사용하신 이유가 있으신가요??

2021-02-01 02:27 UTC, ddalkigum commented on decorators/utils.py
> +import json
아아 맞아요!! 이 부분은 사용하지 않는 부분인데 같이 들어갔습니다 
삭제하고 올리겠습니다

2021-02-01 02:29 UTC, ddalkigum commented on orders/tests.py
> +        self.order_item.save()
아아 setUpTestData에서 만들고 모든 테스트가 공유하기 때문에 
그럼 따로 생성하는 테스트가 필요할 경우에는 따로 묶어서 setUp으로 해주거나 
양이 많지 않으면 test 내에서 실행하면 되겠네요

2021-02-01 02:30 UTC, ddalkigum commented on products/models.py
> +        return self.price
넵 적용해서 진행해보겠습니다 
나중에 결제 페이지까지 하게된다면 같은 부분이 또 필요해서 따로 뺏엇는데 
데코레이터로 빼서 해볼게요

2021-02-01 02:34 UTC, ddalkigum commented on users/models.py
> +        ExpressionWrapper(Ceil(Sum((F("orderitem__product__price") *
이 부분은 가격이 높지않은 상품을 주문할때
계산후에 뒤에 .0을 달고나오는 경우가 생겨서 
F객체를 사용한 이후에 output filed를 설정해주기 위해서 사용했습니다

2021-02-01 02:49 UTC, ddalkigum commented on products/models.py
> +        return self.price
넵 적용해서 해보겠습니다

2021-02-01 12:47 UTC, ddalkigum commented on products/models.py
> +        return self.price
getter 와 setter에 대해서 공부하느라 pr이 좀 늦었습니다... 
장고에서 Model class에 어떻게 적용을 할 수 있을지 생각해봤는데 
models.Model의 init에 들어가서 수정해보고 해봣는데, 장고에서 어떻게 사용해야할지 감이 잘 안잡혀요 ㅠ

2021-02-01 12:48 UTC, ddalkigum commented on orders/tests.py
> +        self.order_item.save()
이 부분은 setUpTestData에서 product_2를 만들어서
`test_get_user_order_products_none_delivery_price`에 
 order_item하나 추가해서 해결했습니다!

2021-02-02 01:31 UTC, soheon-lee commented on orders/views.py
> +            return JsonResponse({"message":"KEY_ERROR"}, status = 400)
현재 준형님 코드에서 키에러 날 부분이 안보이는 것 같은데 혹시 어떤 상황에서 나나요?

2021-02-02 01:31 UTC, soheon-lee commented on orders/views.py
> +                income_product       = Product.objects.get(id = product_data.get("product_id"))
`product_id` 없으면 어떤 에러 발생하나요?

2021-02-02 01:31 UTC, soheon-lee commented on orders/views.py
> +        order.save()
`0.1`, `0,15`, `3000`과 같은 숫자 상수처리 해주시는 것을 추천드립니다 :)

2021-02-02 01:31 UTC, soheon-lee commented on orders/views.py
> +        context["user_address"]      = user.address if user.address is not None else "서울특별시 마포구 만리재옛깃"
만리재옛git ㅋㅋㅋ

2021-02-02 03:40 UTC, ddalkigum commented on orders/views.py
> +        order.save()
넵!

2021-02-02 03:40 UTC, ddalkigum commented on orders/views.py
> +            return JsonResponse({"message":"KEY_ERROR"}, status = 400)
키에러는 없습니다.... 
에러 나는거 테스트하다보니 다른 에러를 발견해서 다시 올릴게요

2021-02-02 03:40 UTC, ddalkigum commented on orders/views.py
> +        context["user_address"]      = user.address if user.address is not None else "서울특별시 마포구 만리재옛깃"
git ㅋㅋㅋㅋㅋㅋㅋㅋ 어쩐지 ㅋㅋㅋㅋㅋ

2021-02-02 03:50 UTC, ddalkigum commented on orders/views.py
> +                income_product       = Product.objects.get(id = product_data.get("product_id"))
{
    "quantity":1
}
로 보낼경우 `Product.DoesNotExist` 에러 발생합니다 

{
    "produ_id": "",
    "quantity":"2"
}
로 보내게 되면 TypeError 발생합니다

{
    "product_id":"1",
    "quantity":"1"
}

이렇게 보내면 AttibuteError 발생합니다 

에러 추가했습니다!

2021-02-02 04:50 UTC, lordmyshepherd commented on products/models.py
> +        return self.price
잘 적용하셨네요~ 👍

2021-02-02 05:02 UTC, lordmyshepherd approved these changes

2021-02-02 05:02 UTC, lordmyshepherd commented on users/models.py
> +        ExpressionWrapper(Ceil(Sum((F("orderitem__product__price") *
👍👍👍👍

2021-02-02 05:03 UTC, lordmyshepherd commented
LGTM 👍

2021-02-02 05:03 UTC, merged